kind = "mobile"
previewPath = "/"
title = "Mobile App"
version = "1.0.0"
id = "artifacts/mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
name = "expo"
paths = [ "/" ]
localPort = 8099

[services.development]
run = "pnpm --filter @workspace/mobile run dev"

[services.env]
PORT = "8099"
BASE_PATH = "/"
